### PR TITLE
Fix cookie banner error

### PR DESCRIPTION
**Pull request by pabloga265**
A cookie consent banner seems to be blocking the URL input for the proxies

image

### CODE REVIEW

**Comment by pabloga265** [comment]
@Kichi779 I am not a python dev so I am not sure if there is a better way of checking if the element exists, selenium seems to remember clicking on the banner when it chooses the same proxy twice

**Comment by Tremsel** [comment]
i tried to use your version. After 1-2 Minutes it crashes?

**Comment by pabloga265** [comment]
@Tremsel I don't experience the crash, do you have any errors I could see ?

**Comment by Tremsel** [comment]
@pabloga265 actually no, it closes and all chrome.exe processes are closed too.

I'm using the newest chromedriver (121.0.6167.85) and newest chrome (121.0.6167.161)
and the newest packages on python 3.11.

**Pull request closed without merging**
